baseURL = 'https://numbertheory.github.io/resume-site/'
languageCode = "en-us"
title = 'Personal Site'
theme = 'anatole'
contentDir = 'content'

[params]
title = "John-Peter Etcheber"
author = "JP Etcheber"
description = "Call me JP."
profilePicture = "images/profile.jpg"
contentratio = 0.8
customCss = ["css/custom.css"]

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jpetcheber/"


[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/numbertheory"


[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "mastodon"
url = "https://hachyderm.io/@numbertheory"
rel = "me"

[[params.socialIcons]]
icon = "fa-brands fa-letterboxd"
title = "letterboxd"
url = "https://letterboxd.com/jproughcut/films/reviews/"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false